//! Incremental graph update logic.
//!
//! Detects changed files via git diff, re-parses only changed + impacted files,
//! and updates the graph accordingly. Also provides full build and watch mode.

use std::collections::HashSet;
use std::fs;
use std::io::Read as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Duration;

use chrono::Utc;
use log::{error, info, warn};
use notify::RecursiveMode;
use notify_debouncer_mini::{new_debouncer, DebounceEventResult};
use sha2::{Digest, Sha256};
use walkdir::WalkDir;

use crate::error::Result;
use crate::graph::GraphStore;
use crate::parser::CodeParser;
use crate::types::EdgeKind;

// Default ignore patterns
const DEFAULT_IGNORE_PATTERNS: &[&str] = &[
    ".code-review-graph/**",
    "node_modules/**",
    ".git/**",
    "__pycache__/**",
    "*.pyc",
    ".venv/**",
    "venv/**",
    "dist/**",
    "build/**",
    ".next/**",
    "target/**",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "*.db",
    "*.sqlite",
    "*.db-journal",
    "*.db-wal",
];

fn git_timeout() -> Duration {
    let secs: u64 = std::env::var("CRG_GIT_TIMEOUT")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(30);
    Duration::from_secs(secs)
}

/// Walk up from `start` to find the nearest `.git` directory.
pub fn find_repo_root(start: Option<&Path>) -> Option<PathBuf> {
    let start = start
        .map(|p| p.to_path_buf())
        .or_else(|| std::env::current_dir().ok())?;
    let mut current = start.as_path();
    loop {
        if current.join(".git").exists() {
            return Some(current.to_path_buf());
        }
        match current.parent() {
            Some(parent) => current = parent,
            None => return None,
        }
    }
}

/// Find the project root: git repo root if available, otherwise cwd.
pub fn find_project_root(start: Option<&Path>) -> PathBuf {
    find_repo_root(start).unwrap_or_else(|| {
        start
            .map(|p| p.to_path_buf())
            .unwrap_or_else(|| std::env::current_dir().unwrap_or_default())
    })
}

/// Determine the graph binary path for a repository.
/// Creates `.code-review-graph/` directory and inner `.gitignore`.
pub fn get_db_path(repo_root: &Path) -> PathBuf {
    let crg_dir = repo_root.join(".code-review-graph");
    let graph_bin = crg_dir.join("graph.bin.zst");

    if let Err(e) = fs::create_dir_all(&crg_dir) {
        warn!("Could not create {}: {}", crg_dir.display(), e);
    }

    let inner_gitignore = crg_dir.join(".gitignore");
    if !inner_gitignore.exists() {
        let _ = fs::write(
            &inner_gitignore,
            "# Auto-generated by code-review-graph — do not commit graph files.\n\
             # graph.bin.zst and embeddings.bin.zst contain absolute paths and code metadata.\n\
             *\n",
        );
    }

    // Clean up legacy SQLite artefacts
    for name in &["graph.db", "graph.db-wal", "graph.db-shm", "graph.db-journal"] {
        let p = crg_dir.join(name);
        if p.exists() {
            let _ = fs::remove_file(p);
        }
    }
    let legacy_db = repo_root.join(".code-review-graph.db");
    if legacy_db.exists() {
        let _ = fs::remove_file(&legacy_db);
    }
    for suffix in &["-wal", "-shm", "-journal"] {
        let side = repo_root.join(format!(".code-review-graph.db{}", suffix));
        if side.exists() {
            let _ = fs::remove_file(side);
        }
    }

    graph_bin
}

/// Determine the embeddings store path for a repository.
pub fn get_embeddings_db_path(repo_root: &Path) -> PathBuf {
    repo_root
        .join(".code-review-graph")
        .join("embeddings.bin.zst")
}

fn load_ignore_patterns(repo_root: &Path) -> Vec<glob::Pattern> {
    let mut raw: Vec<String> = DEFAULT_IGNORE_PATTERNS.iter().map(|s| s.to_string()).collect();
    let ignore_file = repo_root.join(".code-review-graphignore");
    if let Ok(content) = fs::read_to_string(ignore_file) {
        for line in content.lines() {
            let line = line.trim();
            if !line.is_empty() && !line.starts_with('#') {
                raw.push(line.to_string());
            }
        }
    }
    raw.into_iter()
        .filter_map(|p| glob::Pattern::new(&p).ok())
        .collect()
}

fn should_ignore(path: &str, patterns: &[glob::Pattern]) -> bool {
    patterns.iter().any(|p| p.matches(path))
}

fn is_binary(path: &Path) -> bool {
    let Ok(mut f) = fs::File::open(path) else { return true };
    let mut buf = [0u8; 8192];
    match f.read(&mut buf) {
        Ok(n) => buf[..n].contains(&0u8),
        Err(_) => true,
    }
}

fn sha256_bytes(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}

fn now_iso() -> String {
    Utc::now().format("%Y-%m-%dT%H:%M:%S").to_string()
}

fn run_git(repo_root: &Path, args: &[&str]) -> Option<String> {
    let timeout = git_timeout();
    let repo_root = repo_root.to_path_buf();
    // Clone args into owned Strings so the slice can be moved into the spawned thread.
    let args: Vec<String> = args.iter().map(|s| s.to_string()).collect();
    let (tx, rx) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let result = Command::new("git")
            .args(&args)
            .current_dir(&repo_root)
            .output();
        let _ = tx.send(result);
    });
    match rx.recv_timeout(timeout) {
        Ok(Ok(output)) if output.status.success() => {
            Some(String::from_utf8_lossy(&output.stdout).into_owned())
        }
        Ok(Ok(output)) => {
            // Return stdout even on non-zero exit so callers can handle
            let out = String::from_utf8_lossy(&output.stdout).into_owned();
            if out.is_empty() { None } else { Some(out) }
        }
        _ => None,
    }
}

/// Get list of changed files via `git diff`.
pub fn get_changed_files(repo_root: &Path, base: &str) -> Vec<String> {
    // Try diff against base
    let out = run_git(repo_root, &["diff", "--name-only", base])
        .or_else(|| run_git(repo_root, &["diff", "--name-only", "--cached"]));

    out.map(|s| parse_file_lines(&s)).unwrap_or_default()
}

/// Get all modified files (staged + unstaged + untracked).
pub fn get_staged_and_unstaged(repo_root: &Path) -> Vec<String> {
    let out = match run_git(repo_root, &["status", "--porcelain"]) {
        Some(s) => s,
        None => return vec![],
    };
    let mut files = Vec::new();
    for line in out.lines() {
        if line.len() > 3 {
            let entry = line[3..].trim();
            // Handle renames: "old -> new"
            let entry = if let Some(pos) = entry.find(" -> ") {
                &entry[pos + 4..]
            } else {
                entry
            };
            files.push(entry.to_string());
        }
    }
    files
}

/// Get all files tracked by git.
pub fn get_all_tracked_files(repo_root: &Path) -> Vec<String> {
    run_git(repo_root, &["ls-files"])
        .map(|s| parse_file_lines(&s))
        .unwrap_or_default()
}

fn parse_file_lines(s: &str) -> Vec<String> {
    s.lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty())
        .map(|l| l.to_string())
        .collect()
}

/// Collect all parseable files in the repo, respecting ignore patterns.
pub fn collect_all_files(repo_root: &Path) -> Vec<String> {
    let ignore_patterns = load_ignore_patterns(repo_root);
    let parser = CodeParser::new();

    let tracked = get_all_tracked_files(repo_root);
    let candidates: Vec<String> = if !tracked.is_empty() {
        tracked
    } else {
        // Fallback: walk directory
        WalkDir::new(repo_root)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_type().is_file())
            .filter_map(|e| {
                e.path()
                    .strip_prefix(repo_root)
                    .ok()
                    .map(|p| p.to_string_lossy().replace('\\', "/"))
            })
            .collect()
    };

    let mut files = Vec::new();
    for rel_path in candidates {
        if should_ignore(&rel_path, &ignore_patterns) {
            continue;
        }
        let full_path = repo_root.join(&rel_path);
        if !full_path.is_file() || full_path.is_symlink() {
            continue;
        }
        if parser.detect_language(&full_path).is_none() {
            continue;
        }
        if is_binary(&full_path) {
            continue;
        }
        files.push(rel_path);
    }
    files
}

/// Find files that import from or depend on the given file.
pub fn find_dependents(store: &mut GraphStore, file_path: &str) -> Result<Vec<String>> {
    let mut dependents: HashSet<String> = HashSet::new();

    // IMPORTS_FROM edges where this file is the target
    let edges = store.get_edges_by_target(file_path)?;
    for e in edges {
        if e.kind == EdgeKind::ImportsFrom {
            dependents.insert(e.file_path.clone());
        }
    }

    // CALLS/IMPORTS_FROM/INHERITS/IMPLEMENTS edges targeting nodes in this file
    let nodes = store.get_nodes_by_file(file_path)?;
    for node in &nodes {
        let node_edges = store.get_edges_by_target(&node.qualified_name)?;
        for e in node_edges {
            match e.kind {
                EdgeKind::Calls
                | EdgeKind::ImportsFrom
                | EdgeKind::Inherits
                | EdgeKind::Implements => {
                    dependents.insert(e.file_path.clone());
                }
                _ => {}
            }
        }
    }

    dependents.remove(file_path);
    Ok(dependents.into_iter().collect())
}

/// Result of a build operation.
#[derive(Debug, Clone, serde::Serialize)]
pub struct BuildResult {
    pub files_parsed: usize,
    pub total_nodes: usize,
    pub total_edges: usize,
    pub errors: Vec<BuildError>,
}

/// Result of an incremental update.
#[derive(Debug, Clone, serde::Serialize)]
pub struct UpdateResult {
    pub files_updated: usize,
    pub total_nodes: usize,
    pub total_edges: usize,
    pub changed_files: Vec<String>,
    pub dependent_files: Vec<String>,
    pub errors: Vec<BuildError>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct BuildError {
    pub file: String,
    pub error: String,
}

/// Parse `rel_path` (relative to `repo_root`) and store its nodes/edges.
///
/// Returns `(node_count, edge_count)` on success, or a `BuildError` on failure.
fn parse_and_store_file(
    parser: &CodeParser,
    repo_root: &Path,
    rel_path: &str,
    store: &mut GraphStore,
) -> std::result::Result<(usize, usize), BuildError> {
    let full_path = repo_root.join(rel_path);
    let source = std::fs::read(&full_path).map_err(|e| BuildError {
        file: rel_path.to_owned(),
        error: e.to_string(),
    })?;
    let fhash = sha256_bytes(&source);
    let (nodes, edges) = parser.parse_bytes(&full_path, &source).map_err(|e| {
        warn!("Error parsing {}: {}", rel_path, e);
        BuildError {
            file: rel_path.to_owned(),
            error: e.to_string(),
        }
    })?;
    let n = nodes.len();
    let e = edges.len();
    store
        .store_file_nodes_edges(&full_path.to_string_lossy(), &nodes, &edges, &fhash)
        .map_err(|err| BuildError {
            file: rel_path.to_owned(),
            error: err.to_string(),
        })?;
    Ok((n, e))
}

/// Full rebuild of the entire graph.
pub fn full_build(repo_root: &Path, store: &mut GraphStore) -> Result<BuildResult> {
    let parser = CodeParser::new();
    let files = collect_all_files(repo_root);
    let file_count = files.len();

    // Purge stale files no longer on disk
    let existing_files = store.get_all_files()?;
    let current_abs: HashSet<String> = files
        .iter()
        .map(|f| repo_root.join(f).to_string_lossy().into_owned())
        .collect();
    for stale in existing_files {
        if !current_abs.contains(&stale) {
            store.remove_file_data(&stale)?;
        }
    }

    let mut total_nodes = 0usize;
    let mut total_edges = 0usize;
    let mut errors = Vec::new();

    for (i, rel_path) in files.iter().enumerate() {
        match parse_and_store_file(&parser, repo_root, rel_path, store) {
            Ok((n, e)) => {
                total_nodes += n;
                total_edges += e;
            }
            Err(err) => errors.push(err),
        }
        let idx = i + 1;
        if idx % 50 == 0 || idx == file_count {
            info!("Progress: {}/{} files parsed", idx, file_count);
        }
    }

    store.set_metadata("last_updated", &now_iso())?;
    store.set_metadata("last_build_type", "full")?;
    store.commit()?;

    Ok(BuildResult {
        files_parsed: file_count,
        total_nodes,
        total_edges,
        errors,
    })
}

/// Incremental update: re-parse changed + dependent files only.
pub fn incremental_update(
    repo_root: &Path,
    store: &mut GraphStore,
    base: &str,
    changed_files: Option<Vec<String>>,
) -> Result<UpdateResult> {
    let parser = CodeParser::new();
    let ignore_patterns = load_ignore_patterns(repo_root);

    let changed_files = changed_files.unwrap_or_else(|| get_changed_files(repo_root, base));

    if changed_files.is_empty() {
        return Ok(UpdateResult {
            files_updated: 0,
            total_nodes: 0,
            total_edges: 0,
            changed_files: vec![],
            dependent_files: vec![],
            errors: vec![],
        });
    }

    // Find dependent files
    let mut dependent_files: HashSet<String> = HashSet::new();
    for rel_path in &changed_files {
        let full_path = repo_root.join(rel_path).to_string_lossy().into_owned();
        let deps = find_dependents(store, &full_path)?;
        for d in deps {
            let rel = Path::new(&d)
                .strip_prefix(repo_root)
                .map(|p| p.to_string_lossy().into_owned())
                .unwrap_or(d);
            dependent_files.insert(rel);
        }
    }

    let all_files: HashSet<String> = changed_files.iter().cloned().chain(dependent_files.iter().cloned()).collect();
    let dependent_files: Vec<String> = dependent_files.into_iter().collect();

    let mut total_nodes = 0usize;
    let mut total_edges = 0usize;
    let mut errors = Vec::new();

    for rel_path in &all_files {
        if should_ignore(rel_path, &ignore_patterns) {
            continue;
        }
        let abs_path = repo_root.join(rel_path);
        if !abs_path.is_file() {
            // File deleted
            let _ = store.remove_file_data(&abs_path.to_string_lossy());
            continue;
        }
        if parser.detect_language(&abs_path).is_none() {
            continue;
        }

        // Hash-based skip: avoid re-parsing files whose content hasn't changed.
        let skip = match fs::read(&abs_path) {
            Ok(source) => {
                let fhash = sha256_bytes(&source);
                let existing = store.get_nodes_by_file(&abs_path.to_string_lossy())?;
                existing.first().map(|n| n.file_hash.as_str()) == Some(fhash.as_str())
            }
            Err(_) => false,
        };
        if skip {
            continue;
        }

        match parse_and_store_file(&parser, repo_root, rel_path, store) {
            Ok((n, e)) => {
                total_nodes += n;
                total_edges += e;
            }
            Err(err) => errors.push(err),
        }
    }

    store.set_metadata("last_updated", &now_iso())?;
    store.set_metadata("last_build_type", "incremental")?;
    store.commit()?;

    Ok(UpdateResult {
        files_updated: all_files.len(),
        total_nodes,
        total_edges,
        changed_files,
        dependent_files,
        errors,
    })
}

/// Watch for file changes and auto-update the graph.
pub fn watch(repo_root: &Path, store: &mut GraphStore) -> Result<()> {
    let parser = CodeParser::new();
    let ignore_patterns = load_ignore_patterns(repo_root);
    let repo_root = repo_root.to_path_buf();

    // Wrap store in Arc<Mutex<>> so it can be shared with the event handler.
    // Since GraphStore doesn't implement Send, we use a Mutex on the main thread
    // and process events via a channel.
    let (tx, rx) = std::sync::mpsc::channel::<DebounceEventResult>();

    let mut debouncer = new_debouncer(Duration::from_millis(300), tx)
        .map_err(|e| crate::error::CrgError::Other(e.to_string()))?;

    debouncer
        .watcher()
        .watch(&repo_root, RecursiveMode::Recursive)
        .map_err(|e| crate::error::CrgError::Other(e.to_string()))?;

    info!("Watching {} for changes... (Ctrl+C to stop)", repo_root.display());

    for result in rx {
        let events = match result {
            Ok(evts) => evts,
            Err(e) => {
                error!("Watch error: {:?}", e);
                continue;
            }
        };

        let mut paths_to_update: HashSet<PathBuf> = HashSet::new();
        let mut paths_to_remove: HashSet<PathBuf> = HashSet::new();

        for event in events {
            let path = event.path;
            if path.is_symlink() {
                continue;
            }
            let rel = match path.strip_prefix(&repo_root) {
                Ok(r) => r.to_string_lossy().replace('\\', "/"),
                Err(_) => continue,
            };
            if should_ignore(&rel, &ignore_patterns) {
                continue;
            }
            if path.is_file() {
                if parser.detect_language(&path).is_some() {
                    paths_to_update.insert(path);
                }
            } else {
                // File no longer exists — treat as delete
                paths_to_remove.insert(path);
            }
        }

        for path in paths_to_remove {
            let abs_str = path.to_string_lossy().into_owned();
            if let Err(e) = store.remove_file_data(&abs_str) {
                error!("Error removing {}: {}", abs_str, e);
            } else {
                let rel = path.strip_prefix(&repo_root)
                    .map(|p| p.display().to_string())
                    .unwrap_or_else(|_| abs_str.clone());
                info!("Removed: {}", rel);
                let _ = store.commit();
            }
        }

        for path in paths_to_update {
            if is_binary(&path) {
                continue;
            }
            match fs::read(&path) {
                Ok(source) => {
                    let fhash = sha256_bytes(&source);
                    let abs_str = path.to_string_lossy().into_owned();
                    match parser.parse_bytes(&path, &source) {
                        Ok((nodes, edges)) => {
                            let n = nodes.len();
                            let e = edges.len();
                            if let Err(err) = store.store_file_nodes_edges(&abs_str, &nodes, &edges, &fhash) {
                                error!("Error storing {}: {}", abs_str, err);
                            } else {
                                let _ = store.set_metadata(
                                    "last_updated",
                                    &now_iso(),
                                );
                                let _ = store.commit();
                                let rel = path.strip_prefix(&repo_root)
                                    .map(|p| p.display().to_string())
                                    .unwrap_or_else(|_| abs_str.clone());
                                info!("Updated: {} ({} nodes, {} edges)", rel, n, e);
                            }
                        }
                        Err(err) => error!("Error parsing {}: {}", abs_str, err),
                    }
                }
                Err(err) => error!("Error reading {}: {}", path.display(), err),
            }
        }
    }

    info!("Watch stopped.");
    Ok(())
}

// ---------------------------------------------------------------------------
// Pub re-exports of private helpers (used by server.rs background watcher)
// ---------------------------------------------------------------------------

/// Public wrapper around the private `load_ignore_patterns`.
pub fn load_ignore_patterns_pub(repo_root: &Path) -> Vec<glob::Pattern> {
    load_ignore_patterns(repo_root)
}

/// Public wrapper around the private `should_ignore`.
pub fn should_ignore_pub(path: &str, patterns: &[glob::Pattern]) -> bool {
    should_ignore(path, patterns)
}

/// Public wrapper around the private `is_binary`.
pub fn is_binary_pub(path: &Path) -> bool {
    is_binary(path)
}

/// Public wrapper around the private `sha256_bytes`.
pub fn sha256_bytes_pub(data: &[u8]) -> String {
    sha256_bytes(data)
}
