//! Incremental graph update logic.
//!
//! Detects changed files via git diff, re-parses only changed + impacted files,
//! and updates the graph accordingly. Also provides full build and watch mode.

use std::collections::HashSet;
use std::fs;
use std::io::Read as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Duration;

use chrono::Utc;
use indicatif::{ProgressBar, ProgressStyle};
use log::{error, info, warn};
use notify::RecursiveMode;
use notify_debouncer_mini::{new_debouncer, DebounceEventResult};
use rayon::prelude::*;
use sha2::{Digest, Sha256};
use std::io::IsTerminal as _;
use walkdir::WalkDir;

use crate::error::Result;
use crate::graph::GraphStore;
use crate::parser::CodeParser;
use crate::types::EdgeKind;

// Default ignore patterns
const DEFAULT_IGNORE_PATTERNS: &[&str] = &[
    ".code-review-graph/**",
    "node_modules/**",
    ".git/**",
    "__pycache__/**",
    "*.pyc",
    ".venv/**",
    "venv/**",
    "dist/**",
    "build/**",
    ".next/**",
    "target/**",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "*.db",
    "*.sqlite",
    "*.db-journal",
    "*.db-wal",
];

fn git_timeout() -> Duration {
    let secs: u64 = std::env::var("CRG_GIT_TIMEOUT")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(30);
    Duration::from_secs(secs)
}

/// Walk up from `start` to find the nearest `.git` directory.
pub fn find_repo_root(start: Option<&Path>) -> Option<PathBuf> {
    let start = start
        .map(|p| p.to_path_buf())
        .or_else(|| std::env::current_dir().ok())?;
    let mut current = start.as_path();
    loop {
        if current.join(".git").exists() {
            return Some(current.to_path_buf());
        }
        match current.parent() {
            Some(parent) => current = parent,
            None => return None,
        }
    }
}

/// Find the project root: git repo root if available, otherwise cwd.
pub fn find_project_root(start: Option<&Path>) -> PathBuf {
    find_repo_root(start).unwrap_or_else(|| {
        start
            .map(|p| p.to_path_buf())
            .unwrap_or_else(|| std::env::current_dir().unwrap_or_default())
    })
}

/// Determine the graph binary path for a repository.
/// Creates `.code-review-graph/` directory and inner `.gitignore`.
pub fn get_db_path(repo_root: &Path) -> PathBuf {
    let crg_dir = repo_root.join(".code-review-graph");
    let graph_bin = crg_dir.join("graph.bin.zst");

    if let Err(e) = fs::create_dir_all(&crg_dir) {
        warn!("Could not create {}: {}", crg_dir.display(), e);
    }

    let inner_gitignore = crg_dir.join(".gitignore");
    if !inner_gitignore.exists() {
        let _ = fs::write(
            &inner_gitignore,
            "# Auto-generated by code-review-graph — do not commit graph files.\n\
             # graph.bin.zst and embeddings.bin.zst contain absolute paths and code metadata.\n\
             *\n",
        );
    }

    // Clean up legacy SQLite artefacts
    for name in &["graph.db", "graph.db-wal", "graph.db-shm", "graph.db-journal"] {
        let p = crg_dir.join(name);
        if p.exists() {
            let _ = fs::remove_file(p);
        }
    }
    let legacy_db = repo_root.join(".code-review-graph.db");
    if legacy_db.exists() {
        let _ = fs::remove_file(&legacy_db);
    }
    for suffix in &["-wal", "-shm", "-journal"] {
        let side = repo_root.join(format!(".code-review-graph.db{}", suffix));
        if side.exists() {
            let _ = fs::remove_file(side);
        }
    }

    graph_bin
}

/// Determine the embeddings store path for a repository.
pub fn get_embeddings_db_path(repo_root: &Path) -> PathBuf {
    repo_root
        .join(".code-review-graph")
        .join("embeddings.bin.zst")
}

fn load_ignore_patterns(repo_root: &Path) -> Vec<glob::Pattern> {
    let mut raw: Vec<String> = DEFAULT_IGNORE_PATTERNS.iter().map(|s| s.to_string()).collect();
    let ignore_file = repo_root.join(".code-review-graphignore");
    if let Ok(content) = fs::read_to_string(ignore_file) {
        for line in content.lines() {
            let line = line.trim();
            if !line.is_empty() && !line.starts_with('#') {
                raw.push(line.to_string());
            }
        }
    }
    raw.into_iter()
        .filter_map(|p| glob::Pattern::new(&p).ok())
        .collect()
}

fn should_ignore(path: &str, patterns: &[glob::Pattern]) -> bool {
    patterns.iter().any(|p| p.matches(path))
}

fn is_binary(path: &Path) -> bool {
    let Ok(mut f) = fs::File::open(path) else { return true };
    let mut buf = [0u8; 8192];
    match f.read(&mut buf) {
        Ok(n) => buf[..n].contains(&0u8),
        Err(_) => true,
    }
}

fn sha256_bytes(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}

fn now_iso() -> String {
    Utc::now().format("%Y-%m-%dT%H:%M:%S").to_string()
}

fn run_git(repo_root: &Path, args: &[&str]) -> Option<String> {
    let timeout = git_timeout();
    let repo_root = repo_root.to_path_buf();
    // Clone args into owned Strings so the slice can be moved into the spawned thread.
    let args: Vec<String> = args.iter().map(|s| s.to_string()).collect();
    let (tx, rx) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let result = Command::new("git")
            .args(&args)
            .current_dir(&repo_root)
            .output();
        let _ = tx.send(result);
    });
    match rx.recv_timeout(timeout) {
        Ok(Ok(output)) if output.status.success() => {
            Some(String::from_utf8_lossy(&output.stdout).into_owned())
        }
        Ok(Ok(output)) => {
            // Return stdout even on non-zero exit so callers can handle
            let out = String::from_utf8_lossy(&output.stdout).into_owned();
            if out.is_empty() { None } else { Some(out) }
        }
        _ => None,
    }
}

/// Get list of changed files via `git diff`.
pub fn get_changed_files(repo_root: &Path, base: &str) -> Vec<String> {
    // Try diff against base
    let out = run_git(repo_root, &["diff", "--name-only", base])
        .or_else(|| run_git(repo_root, &["diff", "--name-only", "--cached"]));

    out.map(|s| parse_file_lines(&s)).unwrap_or_default()
}

/// Get all modified files (staged + unstaged + untracked).
pub fn get_staged_and_unstaged(repo_root: &Path) -> Vec<String> {
    let out = match run_git(repo_root, &["status", "--porcelain"]) {
        Some(s) => s,
        None => return vec![],
    };
    let mut files = Vec::new();
    for line in out.lines() {
        if line.len() > 3 {
            let entry = line[3..].trim();
            // Handle renames: "old -> new"
            let entry = if let Some(pos) = entry.find(" -> ") {
                &entry[pos + 4..]
            } else {
                entry
            };
            files.push(entry.to_string());
        }
    }
    files
}

/// Get all files tracked by git.
pub fn get_all_tracked_files(repo_root: &Path) -> Vec<String> {
    run_git(repo_root, &["ls-files"])
        .map(|s| parse_file_lines(&s))
        .unwrap_or_default()
}

fn parse_file_lines(s: &str) -> Vec<String> {
    s.lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty())
        .map(|l| l.to_string())
        .collect()
}

/// Collect all parseable files in the repo, respecting ignore patterns.
pub fn collect_all_files(repo_root: &Path) -> Vec<String> {
    let ignore_patterns = load_ignore_patterns(repo_root);
    let parser = CodeParser::new();

    let tracked = get_all_tracked_files(repo_root);
    let candidates: Vec<String> = if !tracked.is_empty() {
        tracked
    } else {
        // Fallback: walk directory
        WalkDir::new(repo_root)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_type().is_file())
            .filter_map(|e| {
                e.path()
                    .strip_prefix(repo_root)
                    .ok()
                    .map(|p| p.to_string_lossy().replace('\\', "/"))
            })
            .collect()
    };

    let mut files = Vec::new();
    for rel_path in candidates {
        if should_ignore(&rel_path, &ignore_patterns) {
            continue;
        }
        let full_path = repo_root.join(&rel_path);
        if !full_path.is_file() || full_path.is_symlink() {
            continue;
        }
        if parser.detect_language(&full_path).is_none() {
            continue;
        }
        if is_binary(&full_path) {
            continue;
        }
        files.push(rel_path);
    }
    files
}

/// Find files that import from or depend on the given file.
pub fn find_dependents(store: &mut GraphStore, file_path: &str) -> Result<Vec<String>> {
    let mut dependents: HashSet<String> = HashSet::new();

    // IMPORTS_FROM edges where this file is the target
    let edges = store.get_edges_by_target(file_path)?;
    for e in edges {
        if e.kind == EdgeKind::ImportsFrom {
            dependents.insert(e.file_path.clone());
        }
    }

    // CALLS/IMPORTS_FROM/INHERITS/IMPLEMENTS edges targeting nodes in this file
    let nodes = store.get_nodes_by_file(file_path)?;
    for node in &nodes {
        let node_edges = store.get_edges_by_target(&node.qualified_name)?;
        for e in node_edges {
            match e.kind {
                EdgeKind::Calls
                | EdgeKind::ImportsFrom
                | EdgeKind::Inherits
                | EdgeKind::Implements => {
                    dependents.insert(e.file_path.clone());
                }
                _ => {}
            }
        }
    }

    dependents.remove(file_path);
    Ok(dependents.into_iter().collect())
}

/// Result of a build operation.
#[derive(Debug, Clone, serde::Serialize)]
pub struct BuildResult {
    pub files_parsed: usize,
    pub total_nodes: usize,
    pub total_edges: usize,
    pub errors: Vec<BuildError>,
}

/// Result of an incremental update.
#[derive(Debug, Clone, serde::Serialize)]
pub struct UpdateResult {
    pub files_updated: usize,
    pub total_nodes: usize,
    pub total_edges: usize,
    pub changed_files: Vec<String>,
    pub dependent_files: Vec<String>,
    pub errors: Vec<BuildError>,
    /// Qualified names of nodes whose body actually changed (not just file-level changes).
    pub changed_qualified_names: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct BuildError {
    pub file: String,
    pub error: String,
}

/// Parse result from a single file (CPU-bound, no store access).
type ParseResult = std::result::Result<
    (String, Vec<crate::types::NodeInfo>, Vec<crate::types::EdgeInfo>, String),
    BuildError,
>;

/// Parse `rel_path` (relative to `repo_root`) without touching the store.
///
/// This is the parallel-safe half: `CodeParser` is a unit struct that creates a
/// fresh `tree_sitter::Parser` per call, so it is safe to invoke from multiple
/// rayon threads simultaneously.
fn parse_file_parallel(parser: &CodeParser, repo_root: &Path, rel_path: &str) -> ParseResult {
    let full_path = repo_root.join(rel_path);
    let source = std::fs::read(&full_path).map_err(|e| BuildError {
        file: rel_path.to_owned(),
        error: e.to_string(),
    })?;
    let fhash = sha256_bytes(&source);
    let (nodes, edges) = parser.parse_bytes(&full_path, &source).map_err(|e| {
        warn!("Error parsing {}: {}", rel_path, e);
        BuildError {
            file: rel_path.to_owned(),
            error: e.to_string(),
        }
    })?;
    Ok((rel_path.to_owned(), nodes, edges, fhash))
}

/// Parse `rel_path` (relative to `repo_root`) and store its nodes/edges.
///
/// Returns `(node_count, edge_count)` on success, or a `BuildError` on failure.
/// Used by `incremental_update` (sequential, store access required per file).
fn parse_and_store_file(
    parser: &CodeParser,
    repo_root: &Path,
    rel_path: &str,
    store: &mut GraphStore,
) -> std::result::Result<(usize, usize), BuildError> {
    let full_path = repo_root.join(rel_path);
    let source = std::fs::read(&full_path).map_err(|e| BuildError {
        file: rel_path.to_owned(),
        error: e.to_string(),
    })?;
    let fhash = sha256_bytes(&source);
    let (nodes, edges) = parser.parse_bytes(&full_path, &source).map_err(|e| {
        warn!("Error parsing {}: {}", rel_path, e);
        BuildError {
            file: rel_path.to_owned(),
            error: e.to_string(),
        }
    })?;
    let n = nodes.len();
    let e = edges.len();
    store
        .store_file_nodes_edges(&full_path.to_string_lossy(), &nodes, &edges, &fhash)
        .map_err(|err| BuildError {
            file: rel_path.to_owned(),
            error: err.to_string(),
        })?;
    Ok((n, e))
}

/// Full rebuild of the entire graph.
pub fn full_build(repo_root: &Path, store: &mut GraphStore) -> Result<BuildResult> {
    let parser = CodeParser::new();
    let files = collect_all_files(repo_root);
    let file_count = files.len();

    // Purge stale files no longer on disk
    let existing_files = store.get_all_files()?;
    let current_abs: HashSet<String> = files
        .iter()
        .map(|f| repo_root.join(f).to_string_lossy().into_owned())
        .collect();
    for stale in existing_files {
        if !current_abs.contains(&stale) {
            store.remove_file_data(&stale)?;
        }
    }

    // Progress bar — shown only when stderr is a terminal.
    let pb = if std::io::stderr().is_terminal() {
        let bar = ProgressBar::new(file_count as u64);
        bar.set_style(
            ProgressStyle::default_bar()
                .template(
                    "{spinner:.green} [{elapsed_precise}] [{bar:40.cyan/blue}] \
                     {pos}/{len} files ({eta})",
                )
                .unwrap()
                .progress_chars("#>-"),
        );
        bar
    } else {
        ProgressBar::hidden()
    };

    // --- Phase 1: parse in parallel (CPU-bound tree-sitter work) ---
    let parse_results: Vec<ParseResult> = files
        .par_iter()
        .map(|rel_path| {
            let result = parse_file_parallel(&parser, repo_root, rel_path);
            pb.inc(1);
            result
        })
        .collect();

    pb.finish_with_message("parsed");

    // --- Phase 2: apply results to store sequentially (store is not Send) ---
    let mut total_nodes = 0usize;
    let mut total_edges = 0usize;
    let mut errors = Vec::new();

    for result in parse_results {
        match result {
            Ok((rel_path, nodes, edges, fhash)) => {
                let full_path = repo_root.join(&rel_path);
                match store.store_file_nodes_edges(
                    &full_path.to_string_lossy(),
                    &nodes,
                    &edges,
                    &fhash,
                ) {
                    Ok(()) => {
                        total_nodes += nodes.len();
                        total_edges += edges.len();
                    }
                    Err(err) => errors.push(BuildError {
                        file: rel_path,
                        error: err.to_string(),
                    }),
                }
            }
            Err(err) => errors.push(err),
        }
    }

    info!("Parsed {}/{} files", file_count - errors.len(), file_count);

    store.set_metadata("last_updated", &now_iso())?;
    store.set_metadata("last_build_type", "full")?;
    store.commit()?;

    Ok(BuildResult {
        files_parsed: file_count,
        total_nodes,
        total_edges,
        errors,
    })
}

/// Incremental update: re-parse changed + dependent files only.
pub fn incremental_update(
    repo_root: &Path,
    store: &mut GraphStore,
    base: &str,
    changed_files: Option<Vec<String>>,
) -> Result<UpdateResult> {
    let parser = CodeParser::new();
    let ignore_patterns = load_ignore_patterns(repo_root);

    let changed_files = changed_files.unwrap_or_else(|| get_changed_files(repo_root, base));

    if changed_files.is_empty() {
        return Ok(UpdateResult {
            files_updated: 0,
            total_nodes: 0,
            total_edges: 0,
            changed_files: vec![],
            dependent_files: vec![],
            errors: vec![],
            changed_qualified_names: vec![],
        });
    }

    // Find dependent files
    let mut dependent_files: HashSet<String> = HashSet::new();
    for rel_path in &changed_files {
        let full_path = repo_root.join(rel_path).to_string_lossy().into_owned();
        let deps = find_dependents(store, &full_path)?;
        for d in deps {
            let rel = Path::new(&d)
                .strip_prefix(repo_root)
                .map(|p| p.to_string_lossy().into_owned())
                .unwrap_or(d);
            dependent_files.insert(rel);
        }
    }

    let all_files: HashSet<String> = changed_files.iter().cloned().chain(dependent_files.iter().cloned()).collect();
    let dependent_files: Vec<String> = dependent_files.into_iter().collect();

    let mut total_nodes = 0usize;
    let mut total_edges = 0usize;
    let mut errors = Vec::new();
    let mut changed_qualified_names: Vec<String> = Vec::new();

    for rel_path in &all_files {
        if should_ignore(rel_path, &ignore_patterns) {
            continue;
        }
        let abs_path = repo_root.join(rel_path);
        if !abs_path.is_file() {
            // File deleted
            let _ = store.remove_file_data(&abs_path.to_string_lossy());
            continue;
        }
        if parser.detect_language(&abs_path).is_none() {
            continue;
        }

        // Hash-based skip: avoid re-parsing files whose content hasn't changed.
        let skip = match fs::read(&abs_path) {
            Ok(source) => {
                let fhash = sha256_bytes(&source);
                let existing = store.get_nodes_by_file(&abs_path.to_string_lossy())?;
                existing.first().map(|n| n.file_hash.as_str()) == Some(fhash.as_str())
            }
            Err(_) => false,
        };
        if skip {
            continue;
        }

        let abs_path_str = abs_path.to_string_lossy().into_owned();
        let old_hashes = store.get_body_hashes(&abs_path_str);

        match parse_and_store_file(&parser, repo_root, rel_path, store) {
            Ok((n, e)) => {
                total_nodes += n;
                total_edges += e;

                let new_hashes = store.get_body_hashes(&abs_path_str);
                for (qn, new_hash) in &new_hashes {
                    let old_hash = old_hashes.get(qn).map(String::as_str).unwrap_or("");
                    if old_hash != new_hash.as_str() {
                        changed_qualified_names.push(qn.clone());
                    }
                }
                // Deleted nodes also count as changed (callers must be re-checked)
                for qn in old_hashes.keys() {
                    if !new_hashes.contains_key(qn) {
                        changed_qualified_names.push(qn.clone());
                    }
                }
            }
            Err(err) => errors.push(err),
        }
    }

    store.set_metadata("last_updated", &now_iso())?;
    store.set_metadata("last_build_type", "incremental")?;
    store.commit()?;

    Ok(UpdateResult {
        files_updated: all_files.len(),
        total_nodes,
        total_edges,
        changed_files,
        dependent_files,
        errors,
        changed_qualified_names,
    })
}

/// Watch for file changes and auto-update the graph.
pub fn watch(repo_root: &Path, store: &mut GraphStore) -> Result<()> {
    let parser = CodeParser::new();
    let ignore_patterns = load_ignore_patterns(repo_root);
    let repo_root = repo_root.to_path_buf();

    // Wrap store in Arc<Mutex<>> so it can be shared with the event handler.
    // Since GraphStore doesn't implement Send, we use a Mutex on the main thread
    // and process events via a channel.
    let (tx, rx) = std::sync::mpsc::channel::<DebounceEventResult>();

    let mut debouncer = new_debouncer(Duration::from_millis(300), tx)
        .map_err(|e| crate::error::CrgError::Other(e.to_string()))?;

    debouncer
        .watcher()
        .watch(&repo_root, RecursiveMode::Recursive)
        .map_err(|e| crate::error::CrgError::Other(e.to_string()))?;

    info!("Watching {} for changes... (Ctrl+C to stop)", repo_root.display());

    for result in rx {
        let events = match result {
            Ok(evts) => evts,
            Err(e) => {
                error!("Watch error: {:?}", e);
                continue;
            }
        };

        let mut paths_to_update: HashSet<PathBuf> = HashSet::new();
        let mut paths_to_remove: HashSet<PathBuf> = HashSet::new();

        for event in events {
            let path = event.path;
            if path.is_symlink() {
                continue;
            }
            let rel = match path.strip_prefix(&repo_root) {
                Ok(r) => r.to_string_lossy().replace('\\', "/"),
                Err(_) => continue,
            };
            if should_ignore(&rel, &ignore_patterns) {
                continue;
            }
            if path.is_file() {
                if parser.detect_language(&path).is_some() {
                    paths_to_update.insert(path);
                }
            } else {
                // File no longer exists — treat as delete
                paths_to_remove.insert(path);
            }
        }

        for path in paths_to_remove {
            let abs_str = path.to_string_lossy().into_owned();
            if let Err(e) = store.remove_file_data(&abs_str) {
                error!("Error removing {}: {}", abs_str, e);
            } else {
                let rel = path.strip_prefix(&repo_root)
                    .map(|p| p.display().to_string())
                    .unwrap_or_else(|_| abs_str.clone());
                info!("Removed: {}", rel);
                let _ = store.commit();
            }
        }

        for path in paths_to_update {
            if is_binary(&path) {
                continue;
            }
            match fs::read(&path) {
                Ok(source) => {
                    let fhash = sha256_bytes(&source);
                    let abs_str = path.to_string_lossy().into_owned();
                    match parser.parse_bytes(&path, &source) {
                        Ok((nodes, edges)) => {
                            let n = nodes.len();
                            let e = edges.len();
                            if let Err(err) = store.store_file_nodes_edges(&abs_str, &nodes, &edges, &fhash) {
                                error!("Error storing {}: {}", abs_str, err);
                            } else {
                                let _ = store.set_metadata(
                                    "last_updated",
                                    &now_iso(),
                                );
                                let _ = store.commit();
                                let rel = path.strip_prefix(&repo_root)
                                    .map(|p| p.display().to_string())
                                    .unwrap_or_else(|_| abs_str.clone());
                                info!("Updated: {} ({} nodes, {} edges)", rel, n, e);
                            }
                        }
                        Err(err) => error!("Error parsing {}: {}", abs_str, err),
                    }
                }
                Err(err) => error!("Error reading {}: {}", path.display(), err),
            }
        }
    }

    info!("Watch stopped.");
    Ok(())
}

// ---------------------------------------------------------------------------
// Pub re-exports of private helpers (used by server.rs background watcher)
// ---------------------------------------------------------------------------

/// Public wrapper around the private `load_ignore_patterns`.
pub fn load_ignore_patterns_pub(repo_root: &Path) -> Vec<glob::Pattern> {
    load_ignore_patterns(repo_root)
}

/// Public wrapper around the private `should_ignore`.
pub fn should_ignore_pub(path: &str, patterns: &[glob::Pattern]) -> bool {
    should_ignore(path, patterns)
}

/// Public wrapper around the private `is_binary`.
pub fn is_binary_pub(path: &Path) -> bool {
    is_binary(path)
}

/// Public wrapper around the private `sha256_bytes`.
pub fn sha256_bytes_pub(data: &[u8]) -> String {
    sha256_bytes(data)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    // -----------------------------------------------------------------------
    // find_repo_root
    // -----------------------------------------------------------------------

    #[test]
    fn find_repo_root_finds_git_dir() {
        let dir = TempDir::new().unwrap();
        fs::create_dir(dir.path().join(".git")).unwrap();
        let subdir = dir.path().join("src");
        fs::create_dir(&subdir).unwrap();

        let root = find_repo_root(Some(&subdir));
        assert!(root.is_some(), "should find repo root");
        assert_eq!(root.unwrap().canonicalize().unwrap(), dir.path().canonicalize().unwrap());
    }

    #[test]
    fn find_repo_root_returns_none_outside_git() {
        let dir = TempDir::new().unwrap();
        // No .git directory created — should find nothing inside this temp dir.
        // We use a path that is definitely not inside a git repo.
        // Walk up from a newly created leaf dir with no .git anywhere in temp path.
        let leaf = dir.path().join("a").join("b").join("c");
        fs::create_dir_all(&leaf).unwrap();

        // We can't guarantee the system tmp dir is not inside a git repo, so
        // we just verify the function doesn't panic and returns Some or None.
        // The important thing is it terminates.
        let _ = find_repo_root(Some(&leaf));
    }

    // -----------------------------------------------------------------------
    // get_db_path
    // -----------------------------------------------------------------------

    #[test]
    fn get_db_path_creates_crg_directory() {
        let dir = TempDir::new().unwrap();
        let path = get_db_path(dir.path());

        let crg_dir = dir.path().join(".code-review-graph");
        assert!(crg_dir.is_dir(), ".code-review-graph dir should be created");
        assert_eq!(path, crg_dir.join("graph.bin.zst"));
    }

    #[test]
    fn get_db_path_creates_gitignore() {
        let dir = TempDir::new().unwrap();
        get_db_path(dir.path());

        let gitignore = dir.path().join(".code-review-graph").join(".gitignore");
        assert!(gitignore.exists(), ".gitignore should be created inside .code-review-graph");
        let content = fs::read_to_string(&gitignore).unwrap();
        assert!(content.contains('*'), ".gitignore should contain a wildcard");
    }

    // -----------------------------------------------------------------------
    // is_binary_pub
    // -----------------------------------------------------------------------

    #[test]
    fn is_binary_detects_binary_files() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("bin.dat");
        fs::write(&path, b"\x00\x01\x02\x03binary\x00data").unwrap();
        assert!(is_binary_pub(&path), "file with null bytes should be binary");
    }

    #[test]
    fn is_binary_returns_false_for_text() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("text.py");
        fs::write(&path, b"def foo():\n    pass\n").unwrap();
        assert!(!is_binary_pub(&path), "Python source should not be binary");
    }

    // -----------------------------------------------------------------------
    // should_ignore_pub
    // -----------------------------------------------------------------------

    #[test]
    fn should_ignore_matches_node_modules() {
        let patterns = load_ignore_patterns_pub(Path::new("."));
        assert!(
            should_ignore_pub("node_modules/react/index.js", &patterns),
            "node_modules should be ignored"
        );
    }

    #[test]
    fn should_ignore_matches_git_dir() {
        let patterns = load_ignore_patterns_pub(Path::new("."));
        assert!(
            should_ignore_pub(".git/config", &patterns),
            ".git should be ignored"
        );
    }

    #[test]
    fn should_ignore_does_not_ignore_src_files() {
        let patterns = load_ignore_patterns_pub(Path::new("."));
        assert!(
            !should_ignore_pub("src/main.py", &patterns),
            "src/main.py should not be ignored"
        );
    }

    // -----------------------------------------------------------------------
    // sha256_bytes_pub
    // -----------------------------------------------------------------------

    #[test]
    fn sha256_bytes_produces_hex_hash() {
        let hash = sha256_bytes_pub(b"hello world");
        // SHA-256 hex output is always 64 lowercase hex characters
        assert_eq!(hash.len(), 64, "SHA-256 hex output should be 64 characters");
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()), "should be lowercase hex");
        // The SHA-256 of "hello world" is a well-known constant — verify first 16 chars
        assert!(
            hash.starts_with("b94d27b9934d3e08"),
            "SHA-256('hello world') should start with b94d27b9934d3e08, got: {}",
            hash
        );
    }

    #[test]
    fn sha256_bytes_deterministic() {
        let h1 = sha256_bytes_pub(b"test data");
        let h2 = sha256_bytes_pub(b"test data");
        assert_eq!(h1, h2, "hash should be deterministic");
    }

    #[test]
    fn sha256_bytes_different_for_different_input() {
        let h1 = sha256_bytes_pub(b"aaa");
        let h2 = sha256_bytes_pub(b"bbb");
        assert_ne!(h1, h2);
    }

    // -----------------------------------------------------------------------
    // collect_all_files skips ignored paths
    // -----------------------------------------------------------------------

    #[test]
    fn collect_all_files_skips_ignored_paths() {
        let dir = TempDir::new().unwrap();
        // Create a .git dir and a node_modules dir
        fs::create_dir(dir.path().join(".git")).unwrap();
        let nm = dir.path().join("node_modules");
        fs::create_dir(&nm).unwrap();
        fs::write(nm.join("index.js"), b"module.exports = {}").unwrap();

        // Create a legitimate Python file
        fs::write(dir.path().join("main.py"), b"def foo(): pass\n").unwrap();

        let files = collect_all_files(dir.path());
        // node_modules should be excluded
        assert!(
            !files.iter().any(|f| f.contains("node_modules")),
            "node_modules should be excluded from collected files"
        );
    }

    // -----------------------------------------------------------------------
    // full_build on a temp directory
    // -----------------------------------------------------------------------

    /// Check if tree-sitter grammars can be initialized on this system.
    /// Returns false on platforms where the C ABI grammar libraries fail.
    fn parser_works() -> bool {
        let parser = crate::parser::CodeParser::new();
        let path = std::path::Path::new("check.py");
        parser.parse_bytes(path, b"").is_ok()
    }

    #[test]
    fn full_build_on_temp_dir() {
        if !parser_works() { return; }
        let dir = TempDir::new().unwrap();
        // Create a minimal Python file and a Rust file
        fs::write(
            dir.path().join("app.py"),
            b"def hello():\n    return 'hi'\n",
        )
        .unwrap();
        fs::write(
            dir.path().join("lib.rs"),
            b"pub fn add(a: u32, b: u32) -> u32 { a + b }\n",
        )
        .unwrap();

        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();
        let result = full_build(dir.path(), &mut store).unwrap();

        assert!(result.files_parsed >= 2, "should parse at least 2 files");
        assert!(result.total_nodes > 0, "should extract nodes");
        assert!(result.errors.is_empty() || result.errors.len() < result.files_parsed,
            "most files should parse without error");
    }

    // -----------------------------------------------------------------------
    // incremental_update detects changed files via hash
    // -----------------------------------------------------------------------

    #[test]
    fn incremental_update_detects_no_changes_when_unchanged() {
        if !parser_works() { return; }
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("app.py"), b"def foo(): pass\n").unwrap();

        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();
        full_build(dir.path(), &mut store).unwrap();

        // Call incremental with the same files — no hash changes
        let result = incremental_update(
            dir.path(),
            &mut store,
            "HEAD",
            Some(vec!["app.py".to_string()]),
        )
        .unwrap();

        // Since content is unchanged, changed_qualified_names should be empty
        assert!(
            result.changed_qualified_names.is_empty(),
            "unchanged file should produce no changed_qualified_names"
        );
    }

    #[test]
    fn incremental_update_detects_changed_file() {
        if !parser_works() { return; }
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("app.py"), b"def foo(): pass\n").unwrap();

        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();
        full_build(dir.path(), &mut store).unwrap();

        // Modify the file
        fs::write(
            dir.path().join("app.py"),
            b"def foo():\n    return 42\n\ndef bar(): pass\n",
        )
        .unwrap();

        let result = incremental_update(
            dir.path(),
            &mut store,
            "HEAD",
            Some(vec!["app.py".to_string()]),
        )
        .unwrap();

        // foo's body changed, bar is new — both should appear in changed_qualified_names
        assert!(
            !result.changed_qualified_names.is_empty(),
            "modified file should produce changed_qualified_names"
        );
    }

    #[test]
    fn incremental_update_empty_changed_list_returns_zero() {
        let dir = TempDir::new().unwrap();
        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();

        let result = incremental_update(dir.path(), &mut store, "HEAD", Some(vec![])).unwrap();
        assert_eq!(result.files_updated, 0);
        assert_eq!(result.total_nodes, 0);
    }

    // -----------------------------------------------------------------------
    // find_dependents
    // -----------------------------------------------------------------------

    /// Build a minimal NodeInfo for testing (no parser required).
    fn make_node(name: &str, qualified_name: &str, file_path: &str) -> crate::types::NodeInfo {
        crate::types::NodeInfo {
            name: name.to_string(),
            qualified_name: qualified_name.to_string(),
            kind: crate::types::NodeKind::Function,
            file_path: file_path.to_string(),
            line_start: 1,
            line_end: 5,
            language: "python".to_string(),
            is_test: false,
            docstring: String::new(),
            signature: format!("def {}():", name),
            body_hash: sha256_bytes(name.as_bytes()),
        }
    }

    /// Build a Calls edge from `source_qn` (in `file_path`) to `target_qn`.
    fn make_calls_edge(
        source_qn: &str,
        target_qn: &str,
        file_path: &str,
    ) -> crate::types::EdgeInfo {
        crate::types::EdgeInfo {
            source_qualified: source_qn.to_string(),
            target_qualified: target_qn.to_string(),
            kind: crate::types::EdgeKind::Calls,
            file_path: file_path.to_string(),
            line: 3,
        }
    }

    /// Build an ImportsFrom edge from `source_qn` (in `file_path`) to `target_qn`.
    fn make_imports_edge(
        source_qn: &str,
        target_qn: &str,
        file_path: &str,
    ) -> crate::types::EdgeInfo {
        crate::types::EdgeInfo {
            source_qualified: source_qn.to_string(),
            target_qualified: target_qn.to_string(),
            kind: crate::types::EdgeKind::ImportsFrom,
            file_path: file_path.to_string(),
            line: 1,
        }
    }

    /// Populate the store: file A has `func_a` which calls `func_b` in file B.
    fn setup_ab_dependency(
        store: &mut crate::graph::GraphStore,
        abs_a: &str,
        abs_b: &str,
    ) {
        let node_b = make_node("func_b", "func_b", abs_b);
        let node_a = make_node("func_a", "func_a", abs_a);
        let edge_a_calls_b = make_calls_edge("func_a", "func_b", abs_a);

        store
            .store_file_nodes_edges(abs_b, &[node_b], &[], "hash_b")
            .unwrap();
        store
            .store_file_nodes_edges(abs_a, &[node_a], &[edge_a_calls_b], "hash_a")
            .unwrap();
    }

    #[test]
    fn find_dependents_returns_caller_file() {
        let dir = TempDir::new().unwrap();
        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();

        let abs_a = dir.path().join("a.py").to_string_lossy().into_owned();
        let abs_b = dir.path().join("b.py").to_string_lossy().into_owned();

        setup_ab_dependency(&mut store, &abs_a, &abs_b);

        let dependents = find_dependents(&mut store, &abs_b).unwrap();

        assert_eq!(
            dependents.len(),
            1,
            "exactly one file depends on b.py; got: {:?}",
            dependents
        );
        assert_eq!(
            dependents[0], abs_a,
            "a.py should be the dependent of b.py"
        );
    }

    #[test]
    fn find_dependents_returns_empty_for_no_dependents() {
        let dir = TempDir::new().unwrap();
        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();

        let abs_b = dir.path().join("b.py").to_string_lossy().into_owned();
        let node_b = make_node("func_b", "func_b", &abs_b);
        store
            .store_file_nodes_edges(&abs_b, &[node_b], &[], "hash_b")
            .unwrap();

        let dependents = find_dependents(&mut store, &abs_b).unwrap();

        assert!(
            dependents.is_empty(),
            "b.py has no dependents; got: {:?}",
            dependents
        );
    }

    #[test]
    fn find_dependents_excludes_self() {
        // A file should not appear in its own dependents list even if a
        // self-referential edge somehow exists in the graph.
        let dir = TempDir::new().unwrap();
        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();

        let abs_b = dir.path().join("b.py").to_string_lossy().into_owned();
        let node_b = make_node("func_b", "func_b", &abs_b);
        // Edge: func_b calls func_b (self-referential)
        let self_edge = make_calls_edge("func_b", "func_b", &abs_b);
        store
            .store_file_nodes_edges(&abs_b, &[node_b], &[self_edge], "hash_b")
            .unwrap();

        let dependents = find_dependents(&mut store, &abs_b).unwrap();

        assert!(
            !dependents.contains(&abs_b),
            "b.py must not appear in its own dependents list; got: {:?}",
            dependents
        );
    }

    #[test]
    fn find_dependents_returns_multiple_callers() {
        let dir = TempDir::new().unwrap();
        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();

        let abs_a = dir.path().join("a.py").to_string_lossy().into_owned();
        let abs_b = dir.path().join("b.py").to_string_lossy().into_owned();
        let abs_c = dir.path().join("c.py").to_string_lossy().into_owned();

        // b.py defines func_b
        let node_b = make_node("func_b", "func_b", &abs_b);
        store
            .store_file_nodes_edges(&abs_b, &[node_b], &[], "hash_b")
            .unwrap();

        // a.py calls func_b
        let node_a = make_node("func_a", "func_a", &abs_a);
        let edge_a = make_calls_edge("func_a", "func_b", &abs_a);
        store
            .store_file_nodes_edges(&abs_a, &[node_a], &[edge_a], "hash_a")
            .unwrap();

        // c.py also calls func_b
        let node_c = make_node("func_c", "func_c", &abs_c);
        let edge_c = make_calls_edge("func_c", "func_b", &abs_c);
        store
            .store_file_nodes_edges(&abs_c, &[node_c], &[edge_c], "hash_c")
            .unwrap();

        let mut dependents = find_dependents(&mut store, &abs_b).unwrap();
        dependents.sort();

        let mut expected = vec![abs_a.clone(), abs_c.clone()];
        expected.sort();

        assert_eq!(
            dependents, expected,
            "both a.py and c.py should be dependents of b.py"
        );
    }

    #[test]
    fn find_dependents_detects_imports_from_edge() {
        // An ImportsFrom edge at the node level (source imports a symbol from b.py)
        // should also be detected.
        let dir = TempDir::new().unwrap();
        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();

        let abs_a = dir.path().join("a.py").to_string_lossy().into_owned();
        let abs_b = dir.path().join("b.py").to_string_lossy().into_owned();

        let node_b = make_node("MyClass", "MyClass", &abs_b);
        store
            .store_file_nodes_edges(&abs_b, &[node_b], &[], "hash_b")
            .unwrap();

        let node_a = make_node("use_class", "use_class", &abs_a);
        let import_edge = make_imports_edge("use_class", "MyClass", &abs_a);
        store
            .store_file_nodes_edges(&abs_a, &[node_a], &[import_edge], "hash_a")
            .unwrap();

        let dependents = find_dependents(&mut store, &abs_b).unwrap();

        assert!(
            dependents.contains(&abs_a),
            "a.py imports from b.py and should be in dependents; got: {:?}",
            dependents
        );
    }

    // -----------------------------------------------------------------------
    // hash-skip: incremental_update skips unchanged files
    // -----------------------------------------------------------------------

    #[test]
    fn incremental_update_skips_file_when_hash_unchanged() {
        if !parser_works() {
            return;
        }
        let dir = TempDir::new().unwrap();

        // Use git init so collect_all_files works via git ls-files
        std::process::Command::new("git")
            .args(["init"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["config", "user.email", "test@test.com"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(dir.path())
            .output()
            .unwrap();

        let py_content = b"def stable(): return 1\n";
        fs::write(dir.path().join("stable.py"), py_content).unwrap();

        std::process::Command::new("git")
            .args(["add", "stable.py"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["commit", "-m", "init"])
            .current_dir(dir.path())
            .output()
            .unwrap();

        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();
        full_build(dir.path(), &mut store).unwrap();

        // Call incremental with the same unchanged file — hash matches what was stored
        let result = incremental_update(
            dir.path(),
            &mut store,
            "HEAD",
            Some(vec!["stable.py".to_string()]),
        )
        .unwrap();

        // Because the file hash hasn't changed, no body hashes differ
        assert!(
            result.changed_qualified_names.is_empty(),
            "file with unchanged content must produce no changed_qualified_names; got: {:?}",
            result.changed_qualified_names
        );
    }

    #[test]
    fn incremental_update_processes_file_when_hash_changes() {
        if !parser_works() {
            return;
        }
        let dir = TempDir::new().unwrap();

        std::process::Command::new("git")
            .args(["init"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["config", "user.email", "test@test.com"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(dir.path())
            .output()
            .unwrap();

        let original = b"def greet(): return 'hello'\n";
        fs::write(dir.path().join("greet.py"), original).unwrap();

        std::process::Command::new("git")
            .args(["add", "greet.py"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["commit", "-m", "init"])
            .current_dir(dir.path())
            .output()
            .unwrap();

        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();
        full_build(dir.path(), &mut store).unwrap();

        // Modify the file on disk — new content produces a different hash
        let modified = b"def greet(): return 'world'\ndef farewell(): pass\n";
        fs::write(dir.path().join("greet.py"), modified).unwrap();

        let result = incremental_update(
            dir.path(),
            &mut store,
            "HEAD",
            Some(vec!["greet.py".to_string()]),
        )
        .unwrap();

        assert!(
            !result.changed_qualified_names.is_empty(),
            "modified file must produce changed_qualified_names; got: {:?}",
            result.changed_qualified_names
        );
    }

    // -----------------------------------------------------------------------
    // find_dependents drives incremental_update dependent discovery
    // -----------------------------------------------------------------------

    #[test]
    fn incremental_update_includes_dependent_files() {
        if !parser_works() {
            return;
        }
        let dir = TempDir::new().unwrap();
        let db_path = get_db_path(dir.path());
        let mut store = crate::graph::GraphStore::new(&db_path).unwrap();

        // Manually populate the graph: a.py calls func_b defined in b.py
        let abs_a = dir.path().join("a.py").to_string_lossy().into_owned();
        let abs_b = dir.path().join("b.py").to_string_lossy().into_owned();

        // Write actual files so incremental_update can read them
        fs::write(&abs_b, b"def func_b(): return 42\n").unwrap();
        fs::write(&abs_a, b"def func_a(): pass\n").unwrap();

        // Seed the graph with the dependency relationship
        setup_ab_dependency(&mut store, &abs_a, &abs_b);
        store.commit().unwrap();

        // Trigger incremental on b.py — a.py should appear in dependent_files
        let result = incremental_update(
            dir.path(),
            &mut store,
            "HEAD",
            Some(vec!["b.py".to_string()]),
        )
        .unwrap();

        assert!(
            result.dependent_files.contains(&"a.py".to_string())
                || result.dependent_files.iter().any(|f| f.contains("a.py")),
            "a.py should be discovered as a dependent of b.py; dependent_files: {:?}",
            result.dependent_files
        );
    }
}
